sonar.projectKey=bankflow
sonar.projectName=BankFlow Banking Platform
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=bankflow-coverage-report/target/site/jacoco-aggregate/jacoco.xml,bankflow-auth-service/target/site/jacoco/jacoco.xml,bankflow-account-service/target/site/jacoco/jacoco.xml,bankflow-payment-service/target/site/jacoco/jacoco.xml,bankflow-notification-service/target/site/jacoco/jacoco.xml
sonar.exclusions=**/generated/**,**/*Application.java,**/*Config.java,**/constant/**,**/dto/**,**/entity/**
